### PR TITLE
Display item name colors

### PR DESCRIPTION
**Pull request by patrickkwang**
Addresses part of #21

### CODE REVIEW

**Comment by patrickkwang** [comment]
@maximusunc, can you check this with a container? I don't have one...

**Review by maximusunc — CHANGES_REQUESTED** [review]
This is a no-go on containers. Either you can get a container, or I'll take a look.

**Comment by maximusunc** [comment]
According to the docs, there is no `invdata <container_id> ansi`. And I tried a few different syntaxes but no luck. Seems kind of silly that they don't support ansi on the container items.

**Comment by maximusunc** [comment]
Ah, I might be on to something. `invdata <container_id> ansi` does work, but hitting the monitor button doesn't work.

**Review by maximusunc — APPROVED** [review]
I added an if statement in the html. You have any better ideas?

**Comment by patrickkwang** [comment]
How about this?

**Review by maximusunc — APPROVED** [review]
Pefect.

**Pull request merged**
